---
# tasks file for zk.system
# Download my configs
- name: Download my dotfiles
  git:
    repo: "{{ dtrepo }}"
    dest: "{{ dtdir }}"
    clone: True
    update: Yes
- name: change the permissions of the dotfiles repo
  file:
    path: "{{ dtrepo }}"
    state: directory
    owner: zakaria
    group: zakaria
    force: yes
#TODO: change to ssh link in git config
- name: Create the .config folder
  file:
    path: "{{ config_dir }}"
    state: directory
      #- name: link the configs to ~/.config folder
      #  copy:
      #    src: "/home/zakaria/dox/dtfiles/nvim"
      #    dest: "/home/zakaria/.config/nvim"
      #    owner: zakaria
      #    group: zakaria
- name: link the configs to ~/.config folder
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: zakaria
    group: zakaria
    recurse: True
  loop:
    - { src: "{{ dtdir + '/nvim'}}", dest: "{{ config_dir + '/nvim'}}"}
    - { src: "{{ dtdir + '/mpd'}}", dest: "{{ config_dir + '/mpd'}}"}
    - { src: "{{ dtdir + '/x11'}}", dest: "{{ config_dir + '/x11'}}"}
    - { src: "{{ dtdir + '/tmux'}}", dest: "{{ config_dir + '/tmux'}}"}
    - { src: "{{ config_dir + '/x11/xinitrc'}}", dest: "{{ _home + '/.xinitrc' }}"}
# .local {{{
- name: Copy .local folder
  copy:
    src: "{{ dtdir + '/.local' }}"
    dest: "{{ local_dir }}"
#}}}
